[workspace]
members = [
  "debris",
  "debris/backends",
  "debris/common",
  "debris/error",
  "debris/hir",
  "debris/language_server",
  "debris/llir",
  "debris/mir",
  "debris/parser",
  "debris/std",
]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true
