var N = null;var sourcesIndex = {};
sourcesIndex["debris_backends"] = {"name":"","dirs":[{"name":"common","files":["commands.rs","mod.rs"]},{"name":"datapack","files":["backend.rs","mod.rs","stringify.rs"]}],"files":["lib.rs"]};
sourcesIndex["debris_common"] = {"name":"","files":["accessor.rs","ident.rs","input_file.rs","lib.rs","span.rs"]};
sourcesIndex["debris_core"] = {"name":"","dirs":[{"name":"error","files":["mod.rs"]},{"name":"hir","files":["hir_context.rs","hir_impl.rs","hir_nodes.rs","hir_visitor.rs","identifier.rs","mod.rs"]},{"name":"llir","files":["llir_context.rs","llir_impl.rs","llir_nodes.rs","mod.rs","utils.rs"]},{"name":"mir","files":["mir_builder.rs","mir_context.rs","mir_impl.rs","mir_nodes.rs","mod.rs","utils.rs"]},{"name":"objects","files":["mod.rs","obj_bool.rs","obj_bool_static.rs","obj_class.rs","obj_function.rs","obj_integer.rs","obj_integer_static.rs","obj_module.rs","obj_null.rs","obj_string.rs"]}],"files":["compile_context.rs","config.rs","debris_object.rs","lib.rs","namespace.rs","types.rs"]};
sourcesIndex["debris_derive"] = {"name":"","files":["lib.rs","object.rs","utils.rs"]};
sourcesIndex["debris_lang"] = {"name":"","files":["main.rs"]};
sourcesIndex["debris_std"] = {"name":"","files":["lib.rs"]};
sourcesIndex["testing"] = {"name":"","files":["lib.rs"]};
sourcesIndex["vfs"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
