#[derive(Debug, Eq, PartialEq)]
pub enum BuildMode {
    Debug,
    Release,
}

/// Holds data about the user specified configuration
#[derive(Debug, Eq, PartialEq)]
pub struct Config {
    pub project_name: String,
    pub project_description: String,
    pub default_scoreboard_name: String,
    pub build_mode: BuildMode,
}

impl BuildMode {
    pub fn is_release(&self) -> bool {
        matches!(self, BuildMode::Release)
    }

    pub fn is_debug(&self) -> bool {
        matches!(self, BuildMode::Debug)
    }
}

impl Default for Config {
    fn default() -> Self {
        Config {
            project_name: "debris_project".to_string(),
            project_description: "A project generated by debris".to_string(),
            default_scoreboard_name: "debris".to_string(),
            build_mode: BuildMode::Debug,
        }
    }
}
