name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Set git to use LF
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "17"
      
    - name: Install rust
      run: rustup update stable
      
    - name: Run tests
      if: matrix.os == 'ubuntu-latest'
      run: cargo test --verbose --features test_vanilla_server -- --nocapture
    
    - name: Run tests
      if: matrix.os != 'ubuntu-latest'
      run: cargo test --verbose -- --nocapture
  
  static_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rust
      run: rustup update stable
    
    - name: Install clippy
      run: rustup component add clippy
    
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings
  
    - name: Install rustfmt
      run: rustup component add rustfmt
    
    - name: Run rustfmt
      run: cargo fmt -- --check