name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "16"
      
    - name: Install rust
      run: rustup update stable
      
    - name: Run tests
      run: cargo test --verbose --features test_vanilla_server
    
    - name: Install clippy
      run: rustup component add clippy
    
    - name: Run Clippy
      run: cargo clippy --all-targets -- -D warnings
  
    - name: Install rustfmt
      run: rustup component add rustfmt
    
    - name: Run rustfmt
      run: cargo fmt -- --check
